export const cartConstants = {
    ADD_CART_ITEM_REQUEST: 'CREATE_CART_ITEM_REQUEST',
    ADD_CART_ITEM_SUCCESS: 'CREATE_CART_ITEM_SUCCESS',
    ADD_CART_ITEM_FAILURE: 'CREATE_CART_ITEM_FAILURE',

    GET_CART_ITEMS_REQUEST: 'GET_CART_ITEMS_REQUEST',
    GET_CART_ITEMS_SUCCESS: 'GET_CART_ITEMS_SUCCESS',
    GET_CART_ITEMS_FAILURE: 'GET_CART_ITEMS_FAILURE',

    DELETE_CART_ITEM_REQUEST: 'DELETE_CART_ITEMS_REQUEST',
    DELETE_CART_ITEM_SUCCESS: 'DELETE_CART_ITEMS_SUCCESS',
    DELETE_CART_ITEM_FAILURE: 'DELETE_CART_ITEMS_FAILURE',

    CHANGE_CART_ITEM_REQUEST: 'CHANGE_COUNT_CART_ITEM_REQUEST',
    CHANGE_CART_ITEM_SUCCESS: 'CHANGE_COUNT_CART_ITEM_SUCCESS',
    CHANGE_CART_ITEM_FAILURE: 'CHANGE_COUNT_CART_ITEM_FAILURE',

}