export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CATEGORY_CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CATEGORY_CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CATEGORY_CREATE_CATEGORY_FAILURE',

    GET_CATEGORY_REQUEST: 'CATEGORY_GET_REQUEST',
    GET_CATEGORY_SUCCESS: 'CATEGORY_GET_SUCCESS',
    GET_CATEGORY_FAILURE: 'CATEGORY_GET_FAILURE',

    DELETE_REQUEST:'CATEGORY_DELETE_REQUEST',
    DELETE_SUCCESS:'CATEGORY_DELETE_SUCCESS',
    DELETE_FAILURE: 'CATEGORY_DELETE_FAILURE',

}