export const categoryConstants = {
    CREATE_CATEGORY_REQUEST: 'CREATE_CATEGORY_REQUEST',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILURE: 'CREATE_CATEGORY_FAILURE',

    GET_CATEGORY_REQUEST: 'CATEGORY_GET_REQUEST',
    GET_CATEGORY_SUCCESS: 'CATEGORY_GET_SUCCESS',
    GET_CATEGORY_FAILURE: 'CATEGORY_GET_FAILURE',

    DELETE_CATEGORY_REQUEST: 'DELETE_CATEGORY_REQUEST',
    DELETE_CATEGORY_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    DELETE_CATEGORY_FAILURE: 'CATEGORY_DELETE_FAILURE',

}