export const productConstants = {
    CREATE_PRODUCT_REQUEST: 'PRODUCT_CREATE_REQUEST',
    CREATE_PRODUCT_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    CREATE_PRODUCT_FAILURE: 'PRODUCT_CREATE_FAILURE',

    GET_PRODUCT_REQUEST: 'PRODUCT_GET_REQUEST',
    GET_PRODUCT_SUCCESS: 'PRODUCT_GET_SUCCESS',
    GET_PRODUCT_FAILURE: 'PRODUCT_GET_FAILURE',

    GETALL_PRODUCTS_REQUEST: 'GETALL_PRODUCTS_REQUEST',
    GETALL_PRODUCTS_SUCCESS: 'GETALL_PRODUCTS_SUCCESS',
    GETALL_PRODUCTS_FAILURE: 'GETALL_PRODUCTS_FAILURE',

    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',

    ADD_PRODUCT_IMAGE_REQUEST: 'ADD_PRODUCT_IMAGE_REQUEST',
    ADD_PRODUCT_IMAGE_SUCCESS: 'ADD_PRODUCT_IMAGE_SUCCESS',
    ADD_PRODUCT_IMAGE_FAILURE: 'ADD_PRODUCT_IMAGE_FAILURE',

    GET_PRODUCT_IMAGE_REQUEST: 'GET_PRODUCT_IMAGE_REQUEST',
    GET_PRODUCT_IMAGE_SUCCESS: 'GET_PRODUCT_IMAGE_SUCCESS',
    GET_PRODUCT_IMAGE_FAILURE: 'GET_PRODUCT_IMAGE_FAILURE',

    DELETE_PRODUCT_IMAGE_REQUEST: 'DELETE_PRODUCT_IMAGE_REQUEST',
    DELETE_PRODUCT_IMAGE_SUCCESS: 'DELETE_PRODUCT_IMAGE_SUCCESS',
    DELETE_PRODUCT_IMAGE_FAILURE: 'DELETE_PRODUCT_IMAGE_FAILURE',
}