export const userConstants = {
REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    GET_USERBYID_REQUEST: 'USER_GETBYID_REQUEST',
    GET_USERBYID_SUCCESS: 'USER_GETBYID_SUCCESS',
    GET_USERBYID_FAILURE: 'USER_GETBYID_FAILURE',

    LOGIN_USER_REQUEST: 'USERS_LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'USERS_LOGIN_USER_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GET_CURRENT_USER_REQUEST: 'GET_CURRENT_USER_REQUEST',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',
    GET_CURRENT_USER_FAILURE: 'GET_CURRENT_USER_FAILURE',

    DELETE_USER_REQUEST: 'USERS_DELETE_CATEGORY_REQUEST',
    DELETE_USER_SUCCESS: 'USERS_DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'USERS_DELETE_USER_FAILURE'

}